### ISSUE TITLE
app调用支付宝快捷支付插件崩溃主要机型见附件，麻烦帮忙看一下。谢谢。

### ISSUE THREAD

**Issue by pandabo1985** [cnmahj/cnAndroidDocs#1]
java.lang.IllegalStateException: The display list is not valid.
	at android.view.GLES20DisplayList.getNativeDisplayList(GLES20DisplayList.java:41)
	at android.view.GLES20Canvas.drawDisplayList(GLES20Canvas.java:367)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:858)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2089)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1787)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2642)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:4861)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:583)
	at dalvik.system.NativeStart.main(Native Method)
![default](https://cloud.githubusercontent.com/assets/2058938/7467628/34fad984-f32f-11e4-84df-41d5c932a308.jpg)

**Comment by cnmahj** [comment]
你好，我不是源代码的维护者。这个项目是对源代码中的注释进行中文化的项目，没有对代码进行任何的维护工作。
另外，您在调用支付宝插件时出现的问题，先联系支付宝方面可能更快一些。
